# maybe split ruined temple and salt alkymancery regions into upper and lower sections
# the top of ruined temple is completely separate from the rest of the region
# the bottom of salt alkymancery cannot reach the rest of the region
class RegionName:
    menu                        = "Menu"
    ship                        = "Ship"
    shivering_shore             = "Shivering Shore"
    the_festering_banquet       = "The Festering Banquet"
    bandits_pass                = "Bandits' Pass"
    village_of_smiles           = "Village of Smiles"
    the_watching_woods          = "The Watching Woods"
    sunken_keep                 = "Sunken Keep"
    castle_of_storms            = "Castle of Storms"
    red_hall_of_cages           = "Red Hall of Cages"
    hagers_cavern               = "Hager's Cavern"
    mire_of_stench              = "Mire Of Stench"
    fort_beyond_the_mire        = "Fort-Beyond-The-Mire"
    the_far_beach               = "The Far Beach"
    dome_of_the_forgotten       = "Dome of the Forgotten"
    ziggurat_of_dust_upper      = "Ziggurat of Dust (Upper)"
    ziggurat_of_dust_lower      = "Ziggurat of Dust (Lower)"
    the_ruined_temple_upper     = "The Ruined Temple (Upper)"
    the_ruined_temple_lower     = "The Ruined Temple (Lower)"
    crans_pass                  = "Cran's Pass"
    mals_floating_castle        = "Mal's Floating Castle"
    pitchwoods                  = "Pitch Woods"
    the_blackest_vault          = "The Blackest Vault"
    siam_lake                   = "Siam Lake"
    salt_alkymancery_upper      = "Salt Alkymancery (Upper)"
    salt_alkymancery_lower      = "Salt Alkymancery (Lower)"
    crypt_of_dead_gods_upper    = "Crypt of the Dead Gods (Upper)"
    crypt_of_dead_gods_lower    = "Crypt of the Dead Gods (Lower)"
    the_still_palace            = "The Still Palace"
